### ISSUE TITLE
./configure while arm build error

### ISSUE THREAD

**Issue by derhier** [wong-fi-hung/termux-miner#21]
Hey, i get following erros while trying to build it:

./configure: 3718: Some: not found
./configure: 3: Syntax error: Unterminated quoted string

i fixed line 3718 myself, but cant figure out the second one

**Comment by wong-fi-hung** [comment]
> 00 - Choose Debian or Ubuntu terminal
> 
> 01- su
> 
> 02- apt update && apt dist-upgrade
> 
> 03 - apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev zlib1g-dev make g++ libtool git
> 
> 04- git clone https://github.com/wong-fi-hung/termux-miner
> 
> 05- cd termux-miner
> 
> 06- build-android.sh
> 
> 07- Now you can start mine!!!
> 
> ./cpuminer -a AlgoritmYouWant -o stratum+tcp://PoolOfYourChoose -u YourWallet -p c=CoinSymbol

thanks for the provided answer, where i'am too late to see the issue.
so, i'am sorry...
for gcc or g++ package, please replace with build-essential instead for the builder tools both in the debian or ubuntu.
this mean to automatically install the needed package for build-essental tools, sepecially gcc and g++.
if the device older than armv8/aarch64 use build-linux-arm.sh, which in this script assembly language compilation was disabled due to succesful build.
and for mining pasword, please read instruction guide given from the pool you choose.
